version: "3"

networks:
  redis-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    depends_on:
      - redis
    networks:
      - redis-network

  redis-cli:
    build:
      dockerfile: redis.dockerfile
      context: docker/redis/data
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 5
        sh /usr/local/insert.sh
      "
    depends_on:
      - redis
    networks:
      - redis-network